version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: aggregationdata
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

networks: 
    mongo-compose-network:
      driver: bridge